/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict IndoPolaris discipline tags for a document
         * @description Auto-tag `text` (1–5000 characters) with IndoPolaris discipline tags.
         *
         *     Returns `predictedTags` (at or above the confidence threshold) and
         *     `confidenceScores` for every label. An empty `predictedTags` is a valid
         *     answer meaning "no confident tag" — the Node side then stores the record
         *     with tagging pending rather than attaching a weak guess (Section 6).
         */
        post: operations["classify_classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record engagement and update the arm posterior
         * @description Fold one engagement observation into its arm's Beta posterior.
         *
         *     The write is two statements in one transaction: the `EngagementEvent`
         *     row and the `BanditArmState` update. They cannot come apart — see
         *     `db.record_feedback`.
         *
         *     `recorded: false` in the response means the observation was *not*
         *     persisted (no DATABASE_URL configured, or the insert failed). That is a
         *     200, not a 500: the caller has a genuine measurement either way, and
         *     raising would misrepresent a lost write as a bad request. The distinction
         *     matters — a false here means the bandit will not learn from this event,
         *     which someone has to notice.
         */
        post: operations["feedback_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness, model artifact and database reachability
         * @description Docker's healthcheck and Node's startup probe both read this.
         *
         *     `ok` requires the model to be loaded. The database is reported but does
         *     not gate the status: an unconfigured database is a valid local-dev mode,
         *     and failing readiness on it would make the container flap instead of
         *     letting the service serve predictions without an audit trail.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Thompson-sampled channel and time-slot for the next publish
         * @description Pick where and when to publish.
         *
         *     Samples Beta(alpha, beta) once per arm and returns the argmax. Reads
         *     `BanditArmState` on every call — no in-memory cache — because the
         *     posteriors are the shared state between this service and any other
         *     writer, and a cached copy would recommend from a snapshot the rest of
         *     the system has already moved past.
         *
         *     `exclude` is a comma-separated list of arms to hold back, so a simulator
         *     or an A/B harness can force exploration of a specific arm.
         *
         *     `draftId` is echoed back and otherwise unused: it makes the response
         *     traceable in a log, which is the only reason it exists.
         */
        get: operations["recommend_recommend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArmState
         * @description One arm's posterior, as reported by /recommend.
         * @example {
         *       "alpha": 7.4,
         *       "arm": "instagram_morning",
         *       "beta": 3.1,
         *       "channel": "instagram",
         *       "mean": 0.7048,
         *       "observedMean": 0.7,
         *       "timeSlot": "morning",
         *       "totalPulls": 10,
         *       "totalReward": 7
         *     }
         */
        ArmState: {
            /** Alpha */
            alpha: number;
            /** Arm */
            arm: string;
            /** Beta */
            beta: number;
            /** Channel */
            channel: string;
            /** Mean */
            mean: number;
            /** Observedmean */
            observedMean: number;
            /** Timeslot */
            timeSlot: string;
            /** Totalpulls */
            totalPulls: number;
            /** Totalreward */
            totalReward: number;
        };
        /**
         * ClassifyRequest
         * @example {
         *       "sourceType": "Report",
         *       "text": "We deployed an upward-looking acoustic profiler through 340 m of first-year ice to measure krill swarms during the austral winter, sampling at 1 Hz for 72 hours."
         *     }
         */
        ClassifyRequest: {
            /** Sourceid */
            sourceId?: string | null;
            /**
             * Sourcetype
             * @default Report
             */
            sourceType: string;
            /** Text */
            text: string;
        };
        /**
         * ClassifyResponse
         * @example {
         *       "confidenceScores": {
         *         "Biology / Ecology": 0.62,
         *         "Data Science / Instrumentation": 0.24
         *       },
         *       "modelVersion": "v1",
         *       "predictedTags": [
         *         "Biology / Ecology",
         *         "Data Science / Instrumentation"
         *       ]
         *     }
         */
        ClassifyResponse: {
            /** Confidencescores */
            confidenceScores: {
                [key: string]: number;
            };
            /** Modelversion */
            modelVersion: string;
            /** Predictedtags */
            predictedTags: string[];
        };
        /**
         * ErrorBody
         * @example {
         *       "code": "INVALID_INPUT",
         *       "message": "text: String should have at least 1 character"
         *     }
         */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
        };
        /**
         * ErrorCode
         * @description The three failure modes a caller has to be able to branch on.
         * @enum {string}
         */
        ErrorCode: "INVALID_INPUT" | "MODEL_NOT_LOADED" | "INTERNAL";
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * FeedbackRequest
         * @example {
         *       "channel": "instagram",
         *       "clicks": 84,
         *       "draftId": "clx0a1b2c3d4e5f6g7h8i9j0k1",
         *       "impressions": 1200,
         *       "isSimulated": false,
         *       "timeSlot": "morning"
         *     }
         */
        FeedbackRequest: {
            /** Channel */
            channel: string;
            /** Clicks */
            clicks: number;
            /** Draftid */
            draftId: string;
            /** Impressions */
            impressions: number;
            /**
             * Issimulated
             * @default false
             */
            isSimulated: boolean;
            /** Timeslot */
            timeSlot: string;
        };
        /**
         * FeedbackResponse
         * @example {
         *       "alpha": 8.4,
         *       "arm": "instagram_morning",
         *       "beta": 4.1,
         *       "mean": 0.672,
         *       "recorded": true,
         *       "reward": 0.07,
         *       "totalPulls": 11
         *     }
         */
        FeedbackResponse: {
            /** Alpha */
            alpha: number;
            /** Arm */
            arm: string;
            /** Beta */
            beta: number;
            /** Mean */
            mean: number;
            /** Recorded */
            recorded: boolean;
            /** Reward */
            reward: number;
            /** Totalpulls */
            totalPulls: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Checks */
            checks: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Modelloaded */
            modelLoaded: boolean;
            /** Modelversion */
            modelVersion?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /**
         * RecommendResponse
         * @example {
         *       "arm": "instagram_morning",
         *       "arms": [],
         *       "channel": "instagram",
         *       "expectedReward": 0.7048,
         *       "exploration": 0.8123,
         *       "reason": "highest Thompson sample over 9 arms",
         *       "timeSlot": "morning"
         *     }
         */
        RecommendResponse: {
            /** Arm */
            arm: string;
            /** Arms */
            arms: components["schemas"]["ArmState"][];
            /** Channel */
            channel: string;
            /** Draftid */
            draftId?: string | null;
            /** Expectedreward */
            expectedReward: number;
            /** Exploration */
            exploration: number;
            /** Reason */
            reason: string;
            /** Timeslot */
            timeSlot: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    classify_classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyResponse"];
                };
            };
            /** @description Malformed request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Model artifact not loaded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    feedback_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Malformed request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    recommend_recommend_get: {
        parameters: {
            query?: {
                draftId?: string | null;
                exclude?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
