import "server-only";

import { randomUUID } from "node:crypto";

import { z } from "zod";

import { env } from "@/lib/env";

/**
 * Client for the Python ML service.
 *
 * Types come from `ml-openapi.d.ts`, generated by `npm run ml:types` from the
 * FastAPI OpenAPI document. They are not hand-written: Section 6 identifies
 * schema drift between the two languages as the most common real cause of
 * integration failures, and hand-duplicating a contract is how that drift
 * becomes invisible. Regenerate with:
 *
 *     npm run ml:types
 */

import type { components } from "./ml-openapi";

export type MlClassifyResponse = components["schemas"]["ClassifyResponse"];
export type MlHealthResponse = components["schemas"]["HealthResponse"];
export type MlErrorCode = components["schemas"]["ErrorCode"];

/** Section 5's ClassificationSourceType. Mirrors the Postgres enum. */
export type MlSourceType = "Report" | "Dataset" | "Publication";

/** Section 6: what a caller gets back when the ML service cannot be reached. */
export type MlUnavailableReason =
  | "not_configured"
  | "timeout"
  | "network"
  | "model_not_loaded"
  | "invalid_input"
  | "http_error"
  | "malformed_response";

/**
 * Result of a classification attempt. Exactly one of `result` / `unavailable`
 * is set, so no caller can forget to check for failure — the union makes
 * `if (outcome.unavailable)` the only legal way to ask.
 */
export type ClassifyOutcome =
  | { ok: true; result: MlClassifyResponse; latencyMs: number; attempts: number }
  | { ok: false; unavailable: MlUnavailableReason; detail: string; latencyMs: number; attempts: number };

const ERROR_ENVELOPE = z.object({
  error: z.object({
    code: z.enum(["INVALID_INPUT", "MODEL_NOT_LOADED", "INTERNAL"]),
    message: z.string(),
  }),
});

/**
 * Validate the service's response before trusting it.
 *
 * A service that answers 200 with a body missing `confidenceScores` is worse
 * than one that fails: the caller would render a blank confidence badge and log
 * nothing. Parsing here turns that into an explicit `malformed_response`.
 */
function parseClassifyResponse(payload: unknown): MlClassifyResponse | null {
  const schema = z.object({
    predictedTags: z.array(z.string()),
    confidenceScores: z.record(z.string(), z.number()),
    modelVersion: z.string(),
  });

  const parsed = schema.safeParse(payload);
  if (!parsed.success) {
    return null;
  }

  // A confidence outside [0,1] would render as a 283% badge. Reject rather than
  // clamp: a wrong number is a bug worth surfacing, not smoothing over.
  const scores = Object.values(parsed.data.confidenceScores);
  if (scores.some((score) => !Number.isFinite(score) || score < 0 || score > 1)) {
    return null;
  }

  return parsed.data;
}

type RequestOptions = {
  path: string;
  method: "GET" | "POST";
  body?: unknown;
  signal: AbortSignal;
  requestId?: string;
};

/**
 * One HTTP attempt. Returns the parsed JSON plus the upstream status, or throws.
 *
 * `fetch` is used directly rather than a wrapper library because the two things
 * this needs — a hard timeout that is not a silent 180s hang, and a per-attempt
 * abort — are both one line each here and considerably more code elsewhere.
 */
async function attempt(
  options: RequestOptions,
): Promise<{ status: number; payload: unknown; latencyMs: number }> {
  const { ML_SERVICE_URL } = env();
  const startedAt = performance.now();
  const url = `${ML_SERVICE_URL}${options.path}`;

  const response = await fetch(url, {
    method: options.method,
    headers: {
      // Traces one user action across both services in a single log query. The
      // caller may supply it so its own log line carries the same id.
      "X-Request-ID": options.requestId ?? randomUUID(),
      ...(options.body ? { "Content-Type": "application/json" } : {}),
    },
    body: options.body ? JSON.stringify(options.body) : undefined,
    signal: options.signal,
    // Health and inference are live state; never serve either from a cache.
    cache: "no-store",
  });

  const text = await response.text();
  let payload: unknown = null;
  if (text) {
    try {
      payload = JSON.parse(text);
    } catch {
      payload = null;
    }
  }

  return { status: response.status, payload, latencyMs: performance.now() - startedAt };
}

/**
 * Perform a request with one retry and backoff (Section 6).
 *
 * Retry policy, and why it is not more aggressive:
 *  - retried: connection refused, DNS failure, timeout, 5xx, 429. These are
 *    transient, and the ML service is a soft dependency — one failed retry is
 *    cheaper than an upload that failed.
 *  - NOT retried: 4xx other than 429, and any 2xx. A malformed payload will be
 *    malformed the second time; retrying it just doubles the latency of a
 *    request that was always going to fail.
 */
async function requestWithRetry(
  path: string,
  method: "GET" | "POST",
  body?: unknown,
  requestId?: string,
): Promise<{
  status: number;
  payload: unknown;
  latencyMs: number;
  attempts: number;
  failure?: { reason: MlUnavailableReason; detail: string };
}> {
  const { ML_TIMEOUT_MS } = env();
  const maxAttempts = 2;
  let attempts = 0;
  const startedAt = performance.now();

  for (let attemptNumber = 1; attemptNumber <= maxAttempts; attemptNumber++) {
    attempts = attemptNumber;

    // A fresh controller per attempt: reusing a timed-out one would make the
    // retry fail instantly with the previous attempt's AbortError.
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), ML_TIMEOUT_MS);

    try {
      const result = await attempt({ path, method, body, signal: controller.signal, requestId });

      if (result.status === 503) {
        return {
          ...result,
          attempts,
          failure: {
            reason: "model_not_loaded",
            detail: "ML service has no model artifact loaded",
          },
        };
      }

      if (result.status >= 500 || result.status === 429) {
        // Fall through to the retry below.
        if (attemptNumber < maxAttempts) {
          await sleep(backoffMs(attemptNumber));
          continue;
        }
        return {
          ...result,
          attempts,
          failure: { reason: "http_error", detail: `ML service returned ${result.status}` },
        };
      }

      if (result.status >= 400) {
        const envelope = ERROR_ENVELOPE.safeParse(result.payload);
        return {
          ...result,
          attempts,
          failure: {
            reason: envelope.success ? "invalid_input" : "http_error",
            detail: envelope.success
              ? envelope.data.error.message
              : `ML service returned ${result.status}`,
          },
        };
      }

      return { ...result, attempts };
    } catch (error) {
      const aborted = error instanceof Error && error.name === "AbortError";
      const detail = aborted
        ? `ML service did not respond within ${ML_TIMEOUT_MS}ms`
        : error instanceof Error
          ? error.message
          : String(error);

      if (attemptNumber < maxAttempts) {
        await sleep(backoffMs(attemptNumber));
        continue;
      }
      return {
        status: 0,
        payload: null,
        latencyMs: performance.now() - startedAt,
        attempts,
        failure: { reason: aborted ? "timeout" : "network", detail },
      };
    } finally {
      clearTimeout(timer);
    }
  }

  /* c8 ignore next -- unreachable: the loop always returns on the last attempt */
  return {
    status: 0,
    payload: null,
    latencyMs: performance.now() - startedAt,
    attempts,
    failure: { reason: "network", detail: "exhausted retries" },
  };
}

/** Linear backoff: 250ms after the first failure. Long enough not to hammer a
 * service that is still starting, short enough to stay inside a user-facing
 * upload budget. */
function backoffMs(attemptNumber: number): number {
  return 250 * attemptNumber;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Structured log in the same shape the Python service emits. */
function log(level: "info" | "warn" | "error", message: string, fields: Record<string, unknown>) {
  const line = JSON.stringify({
    ts: new Date().toISOString(),
    level: level.toUpperCase(),
    logger: "indopolaris.ml.client",
    message,
    ...fields,
  });
  if (level === "error") console.error(line);
  else if (level === "warn") console.warn(line);
  else console.log(line);
}

/**
 * Classify a document's discipline tags.
 *
 * **Never throws.** Section 6 requires that a failure here degrades a report to
 * `tagging: "pending"` rather than failing the whole upload — an unreachable ML
 * service is a degraded feature, not a failed one. Every caller must therefore
 * handle `ok: false`.
 */
export async function classify(input: {
  text: string;
  sourceType: MlSourceType;
  sourceId?: string;
}): Promise<ClassifyOutcome> {
  // Enforce the documented 1–5000 character contract on this side too. The
  // service validates as well, but failing here costs no network round trip and
  // cannot be defeated by a client that skips validation.
  const text = input.text.trim();
  if (text.length < 1 || text.length > 5000) {
    return {
      ok: false,
      unavailable: "invalid_input",
      detail: `text must be 1–5000 characters (got ${text.length})`,
      latencyMs: 0,
      attempts: 0,
    };
  }

  const result = await requestWithRetry("/classify", "POST", {
    text,
    sourceType: input.sourceType,
    ...(input.sourceId ? { sourceId: input.sourceId } : {}),
  });

  if (result.failure) {
    log("warn", "classify unavailable", {
      reason: result.failure.reason,
      detail: result.failure.detail,
      attempts: result.attempts,
      latency_ms: Math.round(result.latencyMs),
      source_type: input.sourceType,
    });
    return {
      ok: false,
      unavailable: result.failure.reason,
      detail: result.failure.detail,
      latencyMs: result.latencyMs,
      attempts: result.attempts,
    };
  }

  const parsed = parseClassifyResponse(result.payload);
  if (!parsed) {
    log("error", "classify returned an unusable body", {
      attempts: result.attempts,
      latency_ms: Math.round(result.latencyMs),
      payload_keys:
        result.payload && typeof result.payload === "object"
          ? Object.keys(result.payload)
          : typeof result.payload,
    });
    return {
      ok: false,
      unavailable: "malformed_response",
      detail: "ML service response did not match the ClassifyResponse schema",
      latencyMs: result.latencyMs,
      attempts: result.attempts,
    };
  }

  log("info", "classified", {
    attempts: result.attempts,
    latency_ms: Math.round(result.latencyMs),
    model_version: parsed.modelVersion,
    predicted_tags: parsed.predictedTags,
    source_type: input.sourceType,
  });

  return { ok: true, result: parsed, latencyMs: result.latencyMs, attempts: result.attempts };
}

/**
 * Probe the ML service. Used by `GET /api/ml/health` and the admin dashboard.
 *
 * Kept separate from `classify` so the health proxy can report the upstream
 * body even when it is `degraded` — which a degrade-to-undefined classifier
 * would throw away.
 */
export async function mlHealth(): Promise<{
  reachable: boolean;
  status?: MlHealthResponse["status"];
  modelLoaded?: boolean;
  modelVersion?: string | null;
  checks?: MlHealthResponse["checks"];
  detail: string;
  latencyMs: number;
}> {
  const result = await requestWithRetry("/health", "GET");

  if (result.failure) {
    return {
      reachable: false,
      detail: result.failure.detail,
      latencyMs: result.latencyMs,
    };
  }

  const body = result.payload as MlHealthResponse | null;
  if (!body || typeof body.status !== "string" || typeof body.modelLoaded !== "boolean") {
    return {
      reachable: false,
      detail: "ML service returned an unexpected /health body",
      latencyMs: result.latencyMs,
    };
  }

  return {
    reachable: true,
    status: body.status,
    modelLoaded: body.modelLoaded,
    modelVersion: body.modelVersion ?? null,
    checks: body.checks,
    detail: body.status === "ok" ? "ok" : "ML service is degraded",
    latencyMs: result.latencyMs,
  };
}

/**
 * True when auto-tagging can be attempted at all. Gates the UI affordance.
 *
 * Reads the validated `env()` rather than `process.env` directly: `ML_SERVICE_URL`
 * has a default of `http://127.0.0.1:8000`, so checking `process.env` would report
 * "not configured" on a machine that is perfectly able to reach a service it never
 * had to configure.
 */
export function isMlConfigured(): boolean {
  try {
    return Boolean(env().ML_SERVICE_URL);
  } catch {
    // A malformed URL is a configuration error; treat as unconfigured rather
    // than throwing inside a page render.
    return false;
  }
}

// ---------------------------------------------------------------------------
// Contextual bandit (Section 6): 3 channels x 3 time slots = 9 arms.
//
// Note the asymmetry with `classify`, and it is deliberate. Classification is
// a nice-to-have: a missing service degrades an upload to `tagging: "pending"`
// and the upload still succeeds. Bandit state is shared, mutable operational
// state — if we silently fell back to a locally-invented arm, or retried a write
// twice, we would corrupt the posteriors that every later recommendation is
// drawn from. So these two functions do NOT fall back: they report
// `unavailable` and the caller decides. A recommendation that cannot be made is
// better served by the Beta(1,1) default the service would have returned.
type MlBanditUnavailableReason = Extract<MlUnavailableReason, "not_configured" | "timeout" | "network" | "http_error" | "malformed_response">;

type RecommendOutcome =
  | { ok: true; result: MlRecommendResponse; latencyMs: number }
  | { ok: false; unavailable: MlBanditUnavailableReason; detail: string; latencyMs: number };

const RECOMMEND_RESPONSE = z.object({
  arm: z.string(),
  channel: z.string(),
  timeSlot: z.string(),
  expectedReward: z.number(),
  exploration: z.number(),
  reason: z.string(),
  draftId: z.string().nullish(),
  arms: z.array(
    z.object({
      arm: z.string(),
      channel: z.string(),
      timeSlot: z.string(),
      alpha: z.number(),
      beta: z.number(),
      mean: z.number(),
      observedMean: z.number(),
      totalPulls: z.number(),
      totalReward: z.number(),
    }),
  ),
});

const FEEDBACK_RESPONSE = z.object({
  recorded: z.boolean(),
  arm: z.string(),
  reward: z.number(),
  alpha: z.number(),
  beta: z.number(),
  mean: z.number(),
  totalPulls: z.number(),
});

export type MlArmState = components["schemas"]["ArmState"];
export type MlRecommendResponse = components["schemas"]["RecommendResponse"];
export type MlFeedbackResponse = components["schemas"]["FeedbackResponse"];

export type { RecommendOutcome };

/** Section 6's TargetChannel. Mirrors the Postgres enum and the ML enum. */
export type MlTargetChannel = "website" | "twitter" | "instagram";

/** Section 6's TimeSlot. */
export type MlTimeSlot = "morning" | "afternoon" | "evening";

/**
 * Ask the service which (channel, time slot) to publish to.
 *
 * `exclude` exists for a specific reason: when the operator overrides a
 * suggestion, the chosen arm must still record that it was *shown*, otherwise
 * the bandit records a selection the user never actually saw and the posterior
 * gets credit or blame for the wrong arm.
 */
export async function recommendArm(options?: {
  draftId?: string;
  exclude?: string[];
}): Promise<RecommendOutcome> {
  const params = new URLSearchParams();
  if (options?.draftId) params.set("draftId", options.draftId);
  if (options?.exclude?.length) params.set("exclude", options.exclude.join(","));

  const requestId = randomUUID();
  const query = params.toString();
  const result = await requestWithRetry(
    query ? `/recommend?${query}` : "/recommend",
    "GET",
    undefined,
    requestId,
  );

  const latencyMs = result.latencyMs;
  if (result.failure) {
    return { ok: false, unavailable: result.failure.reason as MlBanditUnavailableReason, detail: result.failure.detail, latencyMs };
  }

  const parsed = RECOMMEND_RESPONSE.safeParse(result.payload);
  if (!parsed.success) {
    return { ok: false, unavailable: "malformed_response", detail: "ML service returned an unexpected /recommend body", latencyMs };
  }

  // `exploration` is what the UI shows to explain an odd choice ("trying
  // twitter_evening because we have little data"). Outside [0,1] would render
  // as a nonsense badge, same rule as confidenceScores above.
  const { expectedReward, exploration } = parsed.data;
  if (![expectedReward, exploration].every((value) => Number.isFinite(value) && value >= 0 && value <= 1)) {
    return { ok: false, unavailable: "malformed_response", detail: "ML service returned out-of-range bandit scores", latencyMs };
  }

  log("info", "bandit.recommend", {
    request_id: requestId,
    arm: parsed.data.arm,
    channel: parsed.data.channel,
    time_slot: parsed.data.timeSlot,
    expected_reward: expectedReward,
    exploration,
    latency_ms: Math.round(latencyMs),
  });

  return { ok: true, result: parsed.data as MlRecommendResponse, latencyMs };
}

/**
 * Record impressions/clicks for a published draft.
 *
 * No retry. `requestWithRetry` retries 5xx, and a retried POST is a *second*
 * EngagementEvent row inflating an arm's pull count — the double-count is
 * invisible in the posterior and permanently skews every future arm choice.
 * One attempt, reported honestly as either recorded or not.
 */
export async function recordEngagement(body: {
  draftId: string;
  channel: MlTargetChannel;
  timeSlot: MlTimeSlot;
  impressions: number;
  clicks: number;
  isSimulated?: boolean;
}): Promise<{ ok: true; result: MlFeedbackResponse; latencyMs: number } | { ok: false; detail: string; latencyMs: number }> {
  const requestId = randomUUID();
  const startedAt = performance.now();
  const controller = new AbortController();
  const { ML_TIMEOUT_MS } = env();
  const timer = setTimeout(() => controller.abort(), ML_TIMEOUT_MS);

  try {
    const { status, payload } = await attempt({
      path: "/feedback",
      method: "POST",
      requestId,
      body: {
        draftId: body.draftId,
        channel: body.channel,
        timeSlot: body.timeSlot,
        impressions: body.impressions,
        clicks: body.clicks,
        // Default to real analytics. Synthetic feedback must be opted into
        // explicitly so a simulator cannot contaminate production posteriors.
        isSimulated: body.isSimulated ?? false,
      },
      signal: controller.signal,
    });

    const latencyMs = performance.now() - startedAt;

    if (status >= 400) {
      const envelope = ERROR_ENVELOPE.safeParse(payload);
      return {
        ok: false,
        detail: envelope.success ? envelope.data.error.message : `ML service returned ${status}`,
        latencyMs,
      };
    }

    const parsed = FEEDBACK_RESPONSE.safeParse(payload);
    if (!parsed.success || !parsed.data.recorded) {
      return {
        ok: false,
        detail: parsed.success
          ? "ML service accepted the request but did not persist the posterior"
          : "ML service returned an unexpected /feedback body",
        latencyMs,
      };
    }

    log("info", "bandit.feedback", {
      request_id: requestId,
      arm: parsed.data.arm,
      reward: parsed.data.reward,
      total_pulls: parsed.data.totalPulls,
      simulated: body.isSimulated ?? false,
      latency_ms: Math.round(latencyMs),
    });

    return { ok: true, result: parsed.data as MlFeedbackResponse, latencyMs };
  } catch (error) {
    const aborted = error instanceof Error && error.name === "AbortError";
    log("warn", "bandit.feedback_failed", {
      request_id: requestId,
      draft_id: body.draftId,
      arm: `${body.channel}_${body.timeSlot}`,
      reason: aborted ? "timeout" : "network",
    });
    return {
      ok: false,
      detail: aborted ? `ML service did not respond within ${ML_TIMEOUT_MS}ms` : error instanceof Error ? error.message : String(error),
      latencyMs: performance.now() - startedAt,
    };
  } finally {
    clearTimeout(timer);
  }
}
